services:
  postgres:
    image: "postgres:16.3-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: redisPrismaNaver2024@
      POSTGRES_DB: tip_cms
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      # Removing PGDATA environment variable since we're handling directory structure differently
    ports:
      - "5433:5432"
    volumes:
      # Using the direct path without PGDATA redirection
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    stop_grace_period: 60s
    shm_size: "256mb"
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.conf"
    security_opt:
      - no-new-privileges:true
    networks:
      - backend

networks:
  backend:
    internal: false
    driver: bridge
    driver_opts:
      encrypt: "true"
