services:
  postgres:
    image: "postgres:16.3-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tip-cms
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
